{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  name: registry-proxy-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    control-plane: controller-manager
{{- end }}
