general:
  resource:
    kind: Connection
    group: registry-proxy.kyma-project.io
    version: v1alpha1
  urlPath: connections
  category: Discovery and Network
  name: Connection
  scope: namespace
  features:
    actions:
      disableCreate: false
      disableDelete: false
  description: >-
    {{[Connection](https://github.tools.sap/kyma/registry-proxy/tree/main/docs)}} defines the Connection resource.

details: #Inside "Resource Details" view
  status:
    body:
      - name: status.conditions
        widget: ConditionList
        source: status.conditions
        fullWidth: true
      - name: status.nodePort
        widget: Text
        source: status.nodePort
      - name: status.proxyURL
        widget: Text
        source: status.proxyURL
  health:
  body:
    - widget: EventList
      filter: "$matchEvents($$, $root.kind, $root.metadata.name)"
      name: events
      defaultType: information

list: #Inside "Connection" list view
# to Add after TimeFromNow widget is updated track progress https://github.com/kyma-project/busola/issues/3938
#  - name: "Age"
#    widget: TimeFromNow
  - name: list.targetHost
    source: spec.targetHost
    widget: Text
  - name: list.configured
    source: status.conditions[type="Configured"].status
    highlights:
      positive:
        - "true"
        - "True"
      warning:
        - "unknown"
        - "Unknown"
      critical:
        - "false"
        - "False"
        - $item < 0
    widget: Badge
  - name: list.running
    source: status.conditions[type="ConnectionDeployed"].status
    highlights:
      positive:
        - "true"
        - "True"
      warning:
        - "unknown"
        - "Unknown"
      critical:
        - "false"
        - "False"
        - $item < 0
    widget: Badge
  - name: list.ready
    source: status.conditions[type="ConnectionReady"].status
    highlights:
      positive:
        - "true"
        - "True"
      warning:
        - "unknown"
        - "Unknown"
      critical:
        - "false"
        - "False"
        - $item < 0
    widget: Badge

form:
  - path: spec.targetHost
    required: true
    name: form.targetHost
  - path: spec.logLevel
    name: form.logLevel
    enum:
        - "debug"
        - "info"
        - "warn"
        - "error"
        - "fatal"
  - path: spec.proxyURL
    name: form.proxyURL
  - path: spec.nodePort
    name: form.nodePort
  - path: spec.locationID
    name: form.locationID

translations:
  en:
    form:
      targetHost: Target Host
      logLevel: Log Level
      proxyURL: Proxy URL
      nodePort: Node Port
      locationID: Location ID
    status:
      conditions: Conditions
      nodePort: Node Port
      proxyURL: Proxy URL
    details:
      state: State
    list:
      state: State
      conditions: Conditions
      configured: Configured
      running: Deployed
      ready: Ready
      targetHost: "Target Host"
