name: kyma-project.io/module/registry-proxy
version:
defaultCR:
manifest:
documentation: "https://github.tools.sap/kyma/registry-proxy/tree/main/docs"
repository: https://github.tools.sap/kyma/registry-proxy.git
security: sec-scanners-config.yaml
manager:
  name: registry-proxy-operator
  group: apps
  version: v1
  kind: Deployment
associatedResources:
  - group: operator.kyma-project.io
    kind: RegistryProxy
    version: v1alpha1
  - group: registry-proxy.kyma-project.io
    kind: Connection
    version: v1alpha1
icons:
  - name: module-icon
    #TODO: Provide icon for registry-proxy
    link: https://raw.githubusercontent.com/kyma-project/kyma/refs/heads/main/docs/assets/logo_icon.svg