name: kyma-project.io/module/registry-proxy
channel: {{ .Channel }}
version: {{ .Version }}
defaultCR: config/samples/default-registry-proxy-cr.yaml
manifest: registry-proxy.yaml
# annotations:
# "operator.kyma-project.io/doc-url": "https://kyma-project.io/#/registry-proxy/user/README"
moduleRepo: https://github.tools.sap/kyma/registry-proxy.git
