name: kyma-project.io/module/registry-proxy
channel: {{ .Channel }}
version: {{ .Version }}
defaultCR: default-registry-proxy-cr.yaml
manifest: registry-proxy-operator.yaml
annotations:
  "operator.kyma-project.io/doc-url": "https://kyma-project.io/#/registry-proxy/user/README"
moduleRepo: https://github.tools.sap/kyma/registry-proxy.git