name: kyma-project.io/module/registry-proxy
version:
defaultCR: default-registry-proxy-cr.yaml
manifest: registry-proxy-operator.yaml
documentation: "https://kyma-project.io/#/registry-proxy/user/README"
repository: https://github.tools.sap/kyma/registry-proxy.git
security: sec-scanners-config.yaml
icons:
  - name: module-icon
    # TODO: provide rp icon
    link: https://raw.githubusercontent.com/kyma-project/kyma/refs/heads/main/docs/assets/logo_icon.svg