module-name: image-pull-reverse-proxy
# rc-tag: 0.0.0
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/image-pull-reverse-proxy:main
  - europe-docker.pkg.dev/kyma-project/prod/image-pull-reverse-proxy-controller:main
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
