module-name: image-pull-reverse-proxy
# rc-tag: 0.0.0
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/image-pull-reverse-proxy:main
  - europe-docker.pkg.dev/kyma-project/prod/image-pull-reverse-proxy-controller:main
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
