module-name: registry-proxy
# rc-tag: 0.0.0
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/registry-proxy-connection:main
  - europe-docker.pkg.dev/kyma-project/prod/registry-proxy-controller:main
mend:
  language: golang-mod
  exclude:
    - "**/tests/**"
    - "**/*_test.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/tests/**"
    - "**/*_test.go"
