{{- if .Values.rbac.enable }}
# permissions for end users to view imagepullreverseproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: imagepullreverseproxy-viewer-role
rules:
  - apiGroups:
      - operator.kyma-project.io
    resources:
      - imagepullreverseproxies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operator.kyma-project.io
    resources:
      - imagepullreverseproxies/status
    verbs:
      - get
{{- end -}}
