{{- if and .Values.rbac.enable .Values.metrics.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: registry-proxy-controller-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
{{- end -}}
