name: "Create k3d cluster"
description: "Action for creating k3d cluster"

# This action expects to be run inside docker with Ubuntu image
# We cannot install programs on the Solinas VM itself
runs:
  using: "composite"
  steps:
    - name: install-k3d
      env:
        K3D_URL: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
        DEFAULT_K3D_VERSION: "v5.7.4"
      shell: sh
      run: |
        apt update
        apt install curl -y
        curl --silent --fail $K3D_URL | TAG=$DEFAULT_K3D_VERSION bash
