name: "Create k3d cluster"
description: "Action for creating k3d cluster"

# This action expects to be run inside docker with Ubuntu image
# We cannot install programs on the Solinas VM itself
runs:
  using: "composite"
  steps:
    - name: install-k3d
      env:
        K3D_URL: https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
        DEFAULT_K3D_VERSION: "v5.7.4"
      shell: sh
      run: |
        echo "path: ${PATH}"
        mkdir -p ./bin
        PATH=$(pwd)/bin:$PATH
        echo "path: ${PATH}"
        export PATH
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o ./bin
        curl --silent --fail $K3D_URL | K3D_INSTALL_DIR=./bin TAG=$DEFAULT_K3D_VERSION bash -s -- "--no-sudo"
        make create-k3d
