# permissions for end users to edit imagepullreverseproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: image-pull-reverse-proxy
    app.kubernetes.io/managed-by: kustomize
  name: imagepullreverseproxy-editor-role
rules:
  - apiGroups:
      - operator.kyma-project.io
    resources:
      - imagepullreverseproxies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.kyma-project.io
    resources:
      - imagepullreverseproxies/status
    verbs:
      - get
