{{- if .Values.certmanager.enable }}
# Self-signed Issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- if .Values.webhook.enable }}
---
# Certificate for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  dnsNames:
    - registry-proxy.{{ .Release.Namespace }}.svc
    - registry-proxy.{{ .Release.Namespace }}.svc.cluster.local
    - registry-proxy-webhook-service.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}
{{- if .Values.metrics.enable }}
---
# Certificate for the metrics
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: metrics-certs
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - registry-proxy.{{ .Release.Namespace }}.svc
    - registry-proxy.{{ .Release.Namespace }}.svc.cluster.local
    - registry-proxy-metrics-service.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert
{{- end }}
{{- end }}
