apiVersion: registry-proxy.kyma-project.io/v1alpha1
kind: Connection
metadata:
  name: registry-proxy-minimal
  namespace: proxy
spec:
  # proxyURL will be automatically retrieved from the Connectivity Proxy module
  target:
    host: "myregistry.kyma:25002"
