name: integration tests

on:
  workflow_call:
    inputs:
      image:
        description: "The image to test"
        required: true
        type: string
      ctrl_image:
        description: "The controller image to test"
        required: true
        type: string

jobs:
  operator-integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: [self-hosted, solinas]
    container:
      image: public.int.repositories.cloud.sap/ubuntu:22.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - name: compute github commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: |
          make run-integration
        env:
          IMG: ${{ inputs.image }}
          CTRL_IMG: ${{ inputs.ctrl_image }}
