name: unit tests

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: [self-hosted, solinas]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - name: run test
        run: make test
