name: push

on:
  push:
    branches: ["main", "release-*"]

jobs:
  builds:
    uses: ./.github/workflows/_build.yaml
    with:
      purpose: "dev"
      img_directory: "prod"
      img_version: ${{ github.sha }}

  integrations:
    needs: builds
    secrets: inherit
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      operator_image: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-operator:${{ github.sha }}
      rp_image: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-controller:${{ github.sha }}
      connection_image: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-connection:${{ github.sha }}
