name: push

on:
  push:
    branches: ["main", "release-*"]

jobs:
  builds:
    uses: ./.github/workflows/_build.yaml

  integrations:
    needs: builds
    secrets: inherit
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-connection:${{ github.sha }}
      ctrl_image: europe-docker.pkg.dev/kyma-project/prod/registry-proxy-controller:${{ github.sha }}
      tag: ${{ github.sha }}
