name: push

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  builds:
    uses: ./.github/workflows/_build.yaml

  integrations:
    needs: builds
    secrets: inherit
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/image-pull-reverse-proxy:PR-${{ github.event.number }}
      ctrl_image: europe-docker.pkg.dev/kyma-project/dev/image-pull-reverse-proxy-controller:PR-${{ github.event.number }}